apiVersion: v1
kind: Secret
metadata:
  name: hiresphere-secrets
  namespace: hiresphere
type: Opaque
stringData:
  COGNITO_USER_POOL_ID: "ap-southeast-1_XXXXXXXXX"
  COGNITO_CLIENT_ID: "your_client_id_here"
  BOOKING_EVENTS_QUEUE_URL: "https://sqs.ap-southeast-1.amazonaws.com/793424482103/hiresphere-booking-events"
