apiVersion: apps/v1
kind: Deployment
metadata:
  name: submission-service
  namespace: hiresphere
spec:
  replicas: 2
  progressDeadlineSeconds: 1800
  selector:
    matchLabels:
      app: submission-service
  template:
    metadata:
      labels:
        app: submission-service
    spec:
      containers:
        - name: submission-service
          image: 793424482103.dkr.ecr.ap-southeast-1.amazonaws.com/hiresphere/submission-service:latest
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: hiresphere-config
            - secretRef:
                name: hiresphere-secrets
          env:
            - name: PORT
              value: "3005"
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: submission-service
  namespace: hiresphere
spec:
  selector:
    app: submission-service
  ports:
    - port: 80
      targetPort: 3005
